apiVersion: apps/v1
kind: Deployment
metadata:
  name: riverkleaner
  namespace: smu-team02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riverkleaner
  template:
    metadata:
      labels:
        app: riverkleaner
        version: v1
    spec:
      containers:
      - name: riverkleaner
        image: yzq1780/riverkleaner:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: 32Mi
        ports:
        - containerPort: 4004
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: riverkleaner-service
  labels:
    app: riverkleaner
spec:
  ports:
  - port: 4004
    name: http
    targetPort: 4004
  selector:
    app: riverkleaner

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: riverkleaner-rule
  namespace: smu-team02
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: riverkleaner
    name: riverkleaner-service
    port: 4004
  rules:
    - path: /.*
      methods: ["GET","POST"]
      mutators: []
      accessStrategies:
      - handler: allow