apiVersion: apps/v1
kind: Deployment
metadata:
  name: riverkleaner
  namespace: smu-team02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riverkleaner
  template:
    metadata:
      labels:
        app: riverkleaner
        version: v1
        sidecar.istio.io/inject: 'false'
    spec:
      imagePullSecrets: []
      containers:
        - name: riverkleaner
          image: yzq1780/riverkleaner:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4004
              protocol: TCP
          resources:
            requests:
              memory: 64Mi
              cpu: 300m
            limits:
              memory: 128Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: riverkleaner-service
  namespace: smu-team02
  uid: 57bc4641-7a33-4172-a618-90710eac6f4c
  resourceVersion: '67171448'
  creationTimestamp: '2022-11-09T07:54:16Z'
  labels:
    app: riverkleaner-app
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"riverkleaner-app"},"name":"riverkleaner-service","namespace":"smu-team02"},"spec":{"ports":[{"name":"http","port":4004,"targetPort":4004}],"selector":{"app":"riverkleaner-app"}}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4004
      targetPort: 4004
  selector:
    app: riverkleaner-app
  clusterIP: 100.104.216.3
  clusterIPs:
    - 100.104.216.3
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app.kubernetes.io/name: riverkleaner-rule
  name: riverkleaner-rule
  namespace: smu-team02
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods: ["GET","POST"]
      path: /.*
  service:
    host: riverkleaner
    name: riverkleaner-service
    port: 4004