kind: Deployment
apiVersion: apps/v1
metadata:
  name: wejoincap
  namespace: smu-team07
  uid: 8c63e709-e55d-4fa4-a7ef-e10ddad5dffc
  resourceVersion: '67156328'
  generation: 1
  creationTimestamp: '2022-10-27T04:06:37Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"wejoincap","namespace":"smu-team07"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wejoincap"}},"template":{"metadata":{"labels":{"app":"wejoincap","version":"v1"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"cpapp-kyma-db-wejoin-secret"}}],"image":"daniellimwaikiat/wejoincap:latest","imagePullPolicy":"Always","name":"wejoincap","ports":[{"containerPort":4004,"name":"http"}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"250m","memory":"32Mi"}}}]}}}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2022-10-27T04:06:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:version': {}
            'f:spec':
              'f:containers':
                'k:{"name":"wejoincap"}':
                  .: {}
                  'f:envFrom': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":4004,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-11-09T07:23:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wejoincap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wejoincap
        version: v1
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - name: wejoincap
          image: 'daniellimwaikiat/wejoincap:latest'
          ports:
            - name: http
              containerPort: 4004
              protocol: TCP
          envFrom:
            - secretRef:
                name: cpapp-kyma-db-wejoin-secret
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-10-27T04:06:46Z'
      lastTransitionTime: '2022-10-27T04:06:37Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "wejoincap-796fbdb7d" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-11-09T07:23:27Z'
      lastTransitionTime: '2022-11-09T07:23:27Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
